name: test_golektruk
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.3.6
  go_router: ^7.1.1
  google_fonts: ^4.0.5
  flutter_hooks: ^0.18.6
  intl: ^0.18.0
  reactive_forms: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
